/*
 * generated by Xtext
 */
package org.testosterone4j.tdsl.ui;

/*
 * #%L
 * org.testosterone4j.tdsl.ui
 * %%
 * Copyright (C) 2015 Axel Ruder
 * %%
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 * #L%
 */

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.testosterone4j.tdsl.ui.contentassist.TDslProposalPriorities;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TDslUiModule extends org.testosterone4j.tdsl.ui.AbstractTDslUiModule {
	public TDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends org.eclipse.xtext.ui.editor.contentassist.IContentProposalPriorities> bindIContentProposalPriorities() {
		return TDslProposalPriorities.class;
	}
}
