/*
 * generated by Xtext
 */
package org.testosterone4j.tdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.testosterone4j.tdsl.ui.contentassist.TDslProposalPriorities;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TDslUiModule extends org.testosterone4j.tdsl.ui.AbstractTDslUiModule {
	public TDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends org.eclipse.xtext.ui.editor.contentassist.IContentProposalPriorities> bindIContentProposalPriorities() {
		return TDslProposalPriorities.class;
	}
}
