/*
* generated by Xtext
*/
package de.msg.xt.mdt.tdsl.ui.contentassist;

import de.msg.xt.mdt.tdsl.ui.contentassist.AbstractTDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TDslProposalProvider extends AbstractTDslProposalProvider {

}
