/*
 * generated by Xtext
 */
package org.testosterone4j;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TdslRuntimeModule extends org.testosterone4j.AbstractTdslRuntimeModule {

}
