/*
* generated by Xtext
*/
package de.msg.xt.mdt.tdsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class TDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
