/*
 * generated by Xtext
 */
package de.msg.xt.mdt.tdsl.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.xbase.ui.labeling.XbaseLabelProvider;

import com.google.inject.Inject;

import de.msg.xt.mdt.tdsl.jvmmodel.MetaModelExtensions;
import de.msg.xt.mdt.tdsl.tDsl.StatementLine;

/**
 * Provides labels for a EObjects.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class TDslLabelProvider extends XbaseLabelProvider {

	@Inject
	MetaModelExtensions metaModelExtensions;

	@Inject
	public TDslLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	String text(StatementLine line) {
		return "Line " + metaModelExtensions.getIndexInParentBlock(line);
	}

	/*
	 * //Labels and icons can be computed like this:
	 * 
	 * String text(MyModel ele) { return "my "+ele.getName(); }
	 * 
	 * String image(MyModel ele) { return "MyModel.gif"; }
	 */
}
