/*
 * generated by Xtext
 */
package de.msg.xt.mdt.tdsl;

import org.eclipse.xtext.xbase.typing.ITypeProvider;

import de.msg.xt.mdt.tdsl.typeprovider.TDslTypeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TDslRuntimeModule extends de.msg.xt.mdt.tdsl.AbstractTDslRuntimeModule {
	
	@Override
	public Class<? extends ITypeProvider> bindITypeProvider() {
		return TDslTypeProvider.class;
	}

}
